version: '3'

services:
  service:
    build: ./app
    volumes:
      - static_volume:/opt/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static_volume:/opt/app/staticfiles
    depends_on:
      - service
    ports:
      - "80:80"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env


volumes:
  postgres_data:
  static_volume: